version: "3.8"

services:
  dashboard_service:
    build: .
    ports:
      - "5054:5054"
    environment:
      - FLASK_APP=run.py
      - FLASK_RUN_HOST=0.0.0.0
      - DEBUG_MODE=true
      - BOOKING_WS_URL=ws://host.docker.internal:5054
      - WS_HOST=0.0.0.0
      - WS_PORT=6789
      - DATABASE_URI=postgresql://neondb_owner:Od9UnVJ2Wvfr@ep-square-star-a8fg370g-pooler.eastus2.azure.neon.tech/neondb?sslmode=require
      - CLOUDINARY_CLOUD_NAME=dxjjigepf
      - CLOUDINARY_API_KEY=181315914336585
      - CLOUDINARY_API_SECRET=DpUMsRVIpXZ4P3pu63cb-jJGwXA
      - SOCKETIO_URL=http://socketio:5054
      - BOOKING_SOCKET_URL=<placeholder>
      - BOOKING_BRIDGE_NAMESPACE=<placeholder>
    volumes:
      - .:/app
    command: ["python", "run.py"]
