BEGIN;

CREATE TABLE IF NOT EXISTS vendor_tax_profiles (
    id SERIAL PRIMARY KEY,
    vendor_id INTEGER NOT NULL REFERENCES vendors(id) ON DELETE CASCADE,
    gst_registered BOOLEAN NOT NULL DEFAULT FALSE,
    gstin VARCHAR(20),
    legal_name VARCHAR(255),
    state_code VARCHAR(2),
    place_of_supply_state_code VARCHAR(2),
    gst_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    gst_rate DOUBLE PRECISION NOT NULL DEFAULT 18,
    tax_inclusive BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_vendor_tax_profile_vendor UNIQUE (vendor_id)
);

CREATE INDEX IF NOT EXISTS ix_vendor_tax_profiles_vendor_id ON vendor_tax_profiles(vendor_id);

ALTER TABLE transactions ADD COLUMN IF NOT EXISTS payment_use_case VARCHAR(100);
ALTER TABLE transactions ADD COLUMN IF NOT EXISTS source_channel VARCHAR(20) NOT NULL DEFAULT 'app';
ALTER TABLE transactions ADD COLUMN IF NOT EXISTS initiated_by_staff_id VARCHAR(100);
ALTER TABLE transactions ADD COLUMN IF NOT EXISTS initiated_by_staff_name VARCHAR(255);
ALTER TABLE transactions ADD COLUMN IF NOT EXISTS initiated_by_staff_role VARCHAR(50);
ALTER TABLE transactions ADD COLUMN IF NOT EXISTS base_amount DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE transactions ADD COLUMN IF NOT EXISTS meals_amount DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE transactions ADD COLUMN IF NOT EXISTS controller_amount DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE transactions ADD COLUMN IF NOT EXISTS waive_off_amount DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE transactions ADD COLUMN IF NOT EXISTS taxable_amount DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE transactions ADD COLUMN IF NOT EXISTS gst_rate DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE transactions ADD COLUMN IF NOT EXISTS cgst_amount DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE transactions ADD COLUMN IF NOT EXISTS sgst_amount DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE transactions ADD COLUMN IF NOT EXISTS igst_amount DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE transactions ADD COLUMN IF NOT EXISTS total_with_tax DOUBLE PRECISION NOT NULL DEFAULT 0;

COMMIT;
